language: node_js
git:
  depth: 10
before_install:
  - npm install -g gulp bower
  - bower install
node_js:
  - "0.10"
notifications:
  email:
    recipients:
      - stargate@buongiorno.com
    #on_success: [always|never|change] # default: change
    #on_failure: [always|never|change] # default: always